// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalkingHeads.Models;

namespace TalkingHeads.Migrations
{
    [DbContext(typeof(ConcertContext))]
    [Migration("20220806153544_concert")]
    partial class concert
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TalkingHeads.Models.Concert", b =>
                {
                    b.Property<int>("ConcertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConcertId");

                    b.ToTable("Concerts");

                    b.HasData(
                        new
                        {
                            ConcertId = 1,
                            Date = new DateTime(1982, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Clarkston, Michigan, USA",
                            Venue = "Pine Knob Music Theater"
                        },
                        new
                        {
                            ConcertId = 2,
                            Date = new DateTime(1982, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Hoffman Estates, Illinois, USA",
                            Venue = "Poplar Creek"
                        },
                        new
                        {
                            ConcertId = 3,
                            Date = new DateTime(1982, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Des Moines, Iowa, USA",
                            Venue = "Civic Center"
                        },
                        new
                        {
                            ConcertId = 4,
                            Date = new DateTime(1982, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Minneapolis, Minnesota, USA",
                            Venue = "Northrop Auditorium"
                        },
                        new
                        {
                            ConcertId = 5,
                            Date = new DateTime(1982, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Staten Island, New York, USA",
                            Venue = "Paramount Theater"
                        },
                        new
                        {
                            ConcertId = 6,
                            Date = new DateTime(1982, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Forrest Hills, New York, USA",
                            Venue = "Tennis Stadium"
                        },
                        new
                        {
                            ConcertId = 7,
                            Date = new DateTime(1982, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Saratoga Springs, New York, USA",
                            Venue = "Performing Arts Center"
                        },
                        new
                        {
                            ConcertId = 8,
                            Date = new DateTime(1982, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Columbia, Maryland, USA",
                            Venue = "Merriweather Post Pavilion"
                        },
                        new
                        {
                            ConcertId = 9,
                            Date = new DateTime(1982, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "West Hartford, Connecticut, USA",
                            Venue = "Agora Ballroom"
                        },
                        new
                        {
                            ConcertId = 10,
                            Date = new DateTime(1982, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Boston, Massachusetts, USA",
                            Venue = "Orpheum Theater"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
